[package]
name = "lab1_rs"
version = "0.1.0"
edition = "2021"
authors = ["meowning_master"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ascii = "1.0.0"
rand = "0.8.4"

[[bin]]
name = "lab1_rs"
path = "src/main.rs"
